src/components/BaseDataTable.vue
src/config/menuConfig.js
src/views/contract/ContractManagementView.vue

close #102 
- 기본적으로 사용 가능한 컴포넌트 데이터 테이블 구현
- 스크롤 기능 넣을건지
- 컴포넌트 한번 보시고 어느 방향으로 수정하는게 좋을지

[Feature] 공통 컴포넌트 데이터 테이블 구현

---

db.json
package-lock.json
package.json
src/components/notice/AddTargetModal.vue
src/components/notice/NoticeList.vue
src/main.js
src/router/index.js
src/views/support/notice/NoticeCreate.vue
src/views/support/notice/NoticeDetail.vue

close #47 , close #48 , close #51 , close #52 
- 팀장 급 이상이어야 공지 사항 작성 가능
- 제목에 [ ] 대괄호 넣으면 bold체 적용, 공지 적용자 선택 할 수 있어서 그 사람들 한테만 공지가 보임
(로그인을 봐꿔가며 테스트 해주세요)
>
- 기존 feature/notice 지우고 해주셔야 합니다.
- 로그인 한 유저 변경 ( 2번 : 팀장, 8번 : 관리자)
- 중요!!!! : 천천히 테스트 해보고 피드백 사항 작성해주세요 ( 테스트 하시고 db.json 변경사항 폐기 해주세요!!!!!!)

[Feat] 공지사항 작성 기능 구현

---

src/components/common/SearchFilterShell.vue
src/components/contract/ContractSearchFields.vue
src/views/contract/ContractManagementView.vue
vite.config.js

[Feature] 계약 페이지 구현

---

src/components/BaseDataTable.vue
src/views/contract/ContractManagementView.vue

close #123 
- 테이블 색상 변경
- 테이블 헤더 드래그 안되게 변경
- 테이블 헤더 호버시 마우스 상태 변경
- 정렬 관련 설명 버튼 추가
- 데이터 및 헤더 중앙 정렬
- 데이터 15개 기준으로 스크롤 구성
- 데이터 로딩시 로딩 화면 구성
- 추가로 작업해야하는것 있으면 말해주시면 감사하겠습니다
- 레디스 키고 백엔드,프론트 둘다 서버 키고 직접 해보시는걸 추천합니다

[Refactor] 데이터 테이블 수정

---

src/api/auth.js
src/components/BaseDataTable.vue
src/components/Header.vue
src/components/contract/ContractDetailModal.vue
src/components/contract/ContractUploadSuccessModal.vue
src/views/contract/ContractManagementView.vue
src/views/contract/ContractUploadModal.vue

close #38 
close #40 
계약서 등록 버튼 누르고 등록 시 성공시 상세조회 페이지로 이동
- 계약 전체 목록에 자동으로 새로고침하여 조회후 추가
- 색같은 경우는 나중에 한번에 다 맞출 예정입니다
- 상세페이지는 이번 PR에 해당 안됨
- 공통 컴포넌트인 테이블에다가 등록 버튼, 총 n건 조회 추가했는데  안쓰시면 코멘트 달아주시면 분리후 제 개인 페이지에 추가하겠습니다

[Feature] 계약 등록 페이지 구현

---

src/components/employee/EmployeeDepartmentList.vue
src/components/employee/EmployeeSearchResult.vue
src/main.js
src/router/index.js
src/stores/auth.js
src/views/employee/EmployeeLayout.vue
src/views/notification/NotificationLayout.vue

> close #145 
> 로그인 시 pinia에 유저 정보를 저장하는데 페이지를 이동할 때 이 정보가 초기화된다는 문제가 있음
> 페이지 이동 시 api 호출을 하도록 수정해 로그인한 유저의 정보를 다시 pinia에 저장, 활용할 수 있도록 함
>

[Refactor] 로그인 로직 일부 개선

---

src/components/employee/EmployeeDepartmentList.vue
src/components/employee/EmployeeSearchResult.vue
src/views/employee/EmployeeLayout.vue

> close #114 
> 사원 검색 기능 백엔드와 연결 및 검색 결과 모달창 구현
>

[Feat] 사원 검색 모달창 컴포넌트 구현

---

src/components/product/ImageUploadModal.vue
src/components/product/ProductDeleteConfirmModal.vue
src/components/product/ProductDetailForm.vue
src/components/product/ProductRegisterCancelModal.vue
src/components/product/ProductRegisterConfirmModal.vue
src/components/product/ProductRegisterForm.vue
src/components/product/ProductSearchFields.vue
src/config/menuConfig.js
src/router/index.js
src/views/product/ProductDetail.vue
src/views/product/ProductList.vue
src/views/product/ProductRegister.vue
src/views/product/ProductUpdate.vue

> BE PR #248 적용하고 테스트 가능합니다
close #27 
close #28 
close #29 
close #30 
close #31 
상품 목록 조회 기능
상품 검색 기능
상품 상세 조회 기능
상품 등록 기능
상품 수정 기능
상품 삭제 기능

[Feat] 상품 도메인 인쇄 기능 제외 완성

---

src/components/BaseDataTable.vue
src/components/common/SearchFilterShell.vue
src/components/contract/ContractDetailModal.vue
src/components/contract/ContractSearchFields.vue
src/config/menuConfig.js
src/views/contract/ContractManagementView.vue
src/views/contractTemplate/ContractTemplateDetailModal.vue
src/views/contractTemplate/ContractTemplateSearchFields.vue
src/views/contractTemplate/ContractTemplateUploadModal.vue
src/views/contractTemplate/ContractTemplateUploadSuccessModal.vue
src/views/contractTemplate/ContractTemplateView.vue
vite.config.js

close #39 #41 #68 #70 #71 #72 
close #40 
- 계약서 양식 전체 조회 페이지
- 계약서 양식 수정 모달
- 계약서 양식 등록 모달
- 계약서 양식 삭제
- 공통 컴포넌트 검색 더보기 구현   
- 계약 상세 조회 구현 (s3연결후 계약서 부분 만들 예정)
계약관리탭 들어가면 더보기 관련해서 수정했습니다 그것도 같이 봐주시면 감사,,

[Feat] : 계약서 양식 페이지 구현 및 공통 컴포넌트 수정

---

src/router/index.js

상품 목록 이외의 페이지인 상태에서 상단 탭 종료 시 홈으로 돌아가지 않는 문제 수정

[Fix] 상품 관리에서 상단 탭 종료 시 홈으로 돌아가지 않는 문제 수정

---

src/main.js

> close #157 
> 공지사항과 문의사항 등록 시 실시간 알림 발생 기능을구현
주요 변경사항:
- 공지사항 등록 시 알림: 대상 사원들에게 "새로운 공지사항이 등록되었습니다" 알림
- 문의사항 등록 시 알림: 관리자에게 "새로운 문의사항이 등록되었습니다" 알림
- 알림 데이터 구조: 타입별로 구분된 알림 메시지와 링크 정보 포함
- 백엔드 연동: 알림 생성 API 호출 로직 추가
1. 공지사항
1-1. 공지사항 작성 (관리자 -> 태그된 사원)
1-2. 알림 발생
2. 문의사항
2-1. 문의사항 작성 - 알림 발생
2-2. 문의사항 답변 작성 - 알림 발생
>

[Feat] 공지사항과 문의사항 등록시 알림 생성

---

src/main.js

> close #159 
> SSE 알림 발생 시점을 명확하게 하기 위해 앱 마운트 리팩토링
>

[Refactor] SSE 알림 발생 시점을 명확하게 하기 위해 앱 마운트 리팩토링

---

src/components/contract/ContractSearchFields.vue
src/layouts/DefaultLayout.vue
src/views/contract/ContractManagementView.vue
src/views/contract/ContractReplaceModal.vue
src/views/salesDashboard/SalesDashboardLayout.vue

- 윤석님 대시보드 조회 페이지 패딩 제거및 배경색 통일
- 계약서 등록시 파일 이름에 버튼 밀리는 경우 수정
- 계약쪽 검색 조건에 월별 금액 ~으로 처리

[Refactor] : 여러가지 자잘한 기능 수정

---

src/components/sales/SalesSearchFields.vue
src/layouts/DefaultLayout.vue
src/router/index.js
src/views/sales/RegisterSales.vue
src/views/sales/SalesView.vue
src/views/salesDashboard/SalesDashboardLayout.vue

> close #162 
> 매출 관리 페이지의 등록 기능을 모달 형태로 개선
- 매출 등록 페이지 → 모달 컴포넌트 변경
- 등록 삭제 권한 분기
>

[Refactor] 매출 관리의 관리자 페이지 ui 일부 개선

---

src/components/Header.vue
src/components/employee/EmployeeDepartmentList.vue
src/components/notice/NoticeList.vue
src/components/qna/QnaList.vue
src/main.js
src/router/index.js
src/stores/auth.js
src/stores/notification.js
src/views/approval/Approval.vue
src/views/employee/EmployeeLayout.vue
src/views/notification/NotificationLayout.vue
src/views/sales/RegisterSales.vue
src/views/sales/SalesView.vue
src/views/support/notice/NoticeCreate.vue
src/views/support/notice/NoticeDetail.vue
src/views/support/notice/NoticeEdit.vue
src/views/support/qna/QnaCreate.vue
src/views/support/qna/QnaDetail.vue
src/views/user/Mypage.vue
src/views/user/ResetPassword.vue

> close #165 #164 
> 사용자 인증 보안을 강화하고 헤더 드롭다운의 사용자 경험을 개선
- 액세스토큰을 로컬스토리지에서 메모리 기반 반응형 변수로 저장 방식 변경
- 드롭다운 외부 클릭 시 자동으로 닫히는 기능 추가
- 페이지 새로고침 시에도 토큰 상태 유지
>

[Refactor] 로그인 - 액세스 토큰 저장방식 변경 및 헤더 드롭다운 ui/ux 일부 개선

---

src/views/user/Mypage.vue

>  close #167 
> 마이페이지 파일 업로드 후 프로필 사진 업데이트 기능
- 드래그 앤 드랍 기능 추가
- 파일 업로드 -> (S3 저장) -> 프로필 사진 업데이트 -> DB 저장  구조 트랜잭션
>

마이페이지에서 프로필 사진 업데이트 시 S3에 사진을 저장하고 내 프로필 사진이 업데이트되도록 구현

---

src/views/contract/ContractManagementView.vue

기존 로컬 파일 업로드 에서 S3로 변경함에 따라 상세조회 페이지 가져오는 방식 수정
백엔드도 브랜체 제걸로 해야 돌아갑니다

[Refactor]  파일 업로드 변경에 따른 페이지 수정

---

src/components/contract/ContractDetailModal.vue
src/views/contract/ContractApprovalRequestModal.vue
src/views/contract/ContractManagementView.vue

- 썸네일 적용및 다운 가능
- 결재 내역 추가
- 결재 창 상태에따른 버튼 수정 및 결재 코멘트 부분 삭제
>

[Refactor] : 계약 관련 수정

---

src/components/common/SearchFilterShell.vue
src/components/contract/ContractDetailModal.vue
src/config/menuConfig.js
src/views/contract/ContractApprovalRequestModal.vue
src/views/contract/ContractManagementView.vue
src/views/contractTemplate/ContractTemplateView.vue
src/views/log/AccessLogView.vue

접히닫히기 버튼  숨기기가능하게 수정
:showToggle="false" 속성 추가하면 됩니다 
각자 페이지에서

[Refactor] : 접기/닫히기버튼 수정

---

server.js
src/api/auth.js

[Env] https 도메인 등록

---

src/api/auth.js
src/components/salesDashboard/YearSalesCard.vue
src/stores/auth.js
src/stores/notification.js
src/views/notification/NotificationLayout.vue
src/views/sales/SalesView.vue
src/views/salesDashboard/SalesDashboardLayout.vue

[Refactor] 콘솔 로그 제거

---

src/views/contract/ContractManagementView.vue

[Refactor] : 계약 반려 적용

---

src/views/contract/ContractManagementView.vue
src/views/contractTemplate/ContractTemplateUploadModal.vue
src/views/contractTemplate/ContractTemplateView.vue

파일업로드 S3관련 Enum타입 수정되며 오류났던기능 정상화
>

[Refactor] : 계약서 양식 기능오류 수정

---

src/views/dashboard/EmployeeDashboard.vue

실적 목표 조회 안되는 문제 수정
실적 목표 조회 시 잘못된 변수 넣던 문제 수정

[Fix] 실적 목표 조회 안되는 문제 수정

---

server.js
src/api/auth.js
src/components/product/ImageUploadModal.vue
src/components/product/ProductDetailForm.vue
src/components/product/ProductRegisterConfirmModal.vue
src/components/product/ProductRegisterForm.vue
src/components/product/ProductUpdateConfirmModal.vue
src/layouts/DefaultLayout.vue
src/views/product/ProductDetail.vue
src/views/product/ProductRegister.vue
vite.config.js

> close #196 
> 상품 등록 시 이미지 업로드 방식 개선, 상품 수정/삭제 시 관리자 권한 분기처리를 추가
1. S3 이미지 업로드 최적화
- 파일 선택 시 미리보기 기능: 파일 선택 시 즉시 S3 업로드하지 않고 Base64 미리보기 생성
- 상품 등록 시점에 S3 업로드: 상품 등록 버튼 클릭 시 파일을 먼저 S3에 업로드 후 상품 정보 등록
- 상품 등록 취소 시 불필요한 파일 업로드 방지
2. 관리자 권한 분기처리
- 관리자 권한 확인 로직: 상품 수정/삭제 시 관리자 권한 검증
- UI 분기처리: 관리자가 아닌 사용자에게는 수정/삭제 버튼 숨김
>

[Refactor] 상품 - S3 이미지 업로드 최적화 및 관리자 권한 분기처리

---

server.js
src/api/auth.js
src/stores/notification.js

배포 시 Express 서버와 Vite가 변수를 인식 하지 못하는 것 수정 -> 변수 하드 코딩
이제 develop 브랜치에서 테스트 시 서로 환경에 맞게 주석을 변경하셔야 합니다.
server.js
src/api/auth.js
src/stores/notification.js
>

[Env] URL 하드 코딩 변경

---

src/stores/notification.js
src/views/log/AccessLogView.vue

[Env] 로그 경로 수정

---

src/components/product/ProductDeleteConfirmModal.vue
src/components/product/ProductDetailForm.vue
src/components/product/ProductRegisterCancelModal.vue
src/components/product/ProductRegisterForm.vue
src/views/product/ProductDetail.vue
src/views/product/ProductList.vue
src/views/product/ProductRegister.vue
src/views/product/ProductUpdate.vue

Refactor: 상품 수정 페이지 개선
Refactor: 상품 상세 페이지 숫자 포맷 추가

[Refactor] 상품 수정 페이지 개선

---

src/views/dashboard/EmployeeDashboard.vue
src/views/user/LoginView.vue

feat : 대시보드 구현

---

src/components/TopTabs.vue
src/main.js
src/stores/tabStore.js

탭에다가 전체 탭 닫기, 현재 탭 제외 닫기 기능 추가

[Refactor] : 탭 전체 닫기 현재창 빼고 닫기 추가

---

.gitignore
server.js
src/api/auth.js
src/components/notification/NotificationDropdown.vue
src/stores/notification.js
src/views/salesDashboard/SalesDashboardLayout.vue
vite.config.js

> close #215 
> 알림 sse 연결이 배포환경에서 끊어지고 재연결되지 않는 문제 해결
> 대시보드 공백 수정
>

[Refactor] 알림 sse 연결이 배포환경에서 끊어지는 문제 수정

---

package.json
src/components/Sidebar.vue
src/config/menuConfig.js
src/views/dashboard/EmployeeDashboard.vue

[Refactor] 실적 대시보드 카드 제목 패딩 수정

---

src/components/contract/ContractDetailModal.vue
src/components/contract/ContractSearchFields.vue
src/views/contract/ContractManagementView.vue
src/views/contractTemplate/ContractTemplateSearchFields.vue
src/views/contractTemplate/ContractTemplateView.vue

→ 숨겨 놨습니다
- 참고
→ 테이블대로 위에 검색 기준 맞출 예정
- 참고

[Refactor] : QA 계약 관련 전체 수정

---

src/components/qna/QnaList.vue
src/views/support/notice/NoticeDetail.vue
src/views/support/qna/QnaDetail.vue

[Refactor] 고객지원 파트 QA 반영

---

src/components/qna/QnaList.vue

필터링 시 1 페이지로 이동하도록 수정
- 필터링 시 비어 있는 페이지 뜨던 현상
-> 필터링 시 1 페이지로 이동하도록 수정
>

[Refactor] 문의사항 필터링 시 1페이지로 가도록 수정

---

src/components/contract/ContractDetailModal.vue
src/router/index.js
src/views/contract/ContractApprovalRequestModal.vue
src/views/contract/ContractManagementView.vue

- 결재중, 결재전, 반려 상태 아니면 전부 결재 요청 비활성화
- 결재 내역에서 결재탭 이동 가능하게 수정
- 계약별 상품 부분 수량에 맞게 총 금액 수정
>

[Refactor] : 계약 상세 조회 페이지 수정

---

src/api/consult.js
src/api/customer.js
src/views/consult/ConsultingView.vue
src/views/customer/CustomerView.vue

백엔드 권한 분기 처리 후 프론트엔드 고객/상담 목록 화면에서 조회되도록 수정

[Fix] 상담, 고객 관리 화면 목록 출력되게 수정

---

src/components/goal/DepartmentGoalSearchFields.vue
src/components/goal/EmployeeGoalSearchFields.vue
src/views/goal/DepartmentGoalList.vue
src/views/goal/EmployeeGoalList.vue

검색 필터 접기 기능 추가
범위 설정하는 검색 필터 물결 표시 및 라벨 단일화
총 렌탈료에 천 단위 구분 쉼표 추가
대상연월 yyyy-MM 형식으로 표시
고객 만족도 점수 표시 수정

[Refactor] 개인 실적 목표, 팀 실적 목표 스타일 수정

---

src/components/goal/DepartmentGoalSearchFields.vue
src/components/goal/EmployeeGoalDeleteModal.vue
src/components/goal/EmployeeGoalSearchFields.vue
src/components/goal/GoalRegisterCancelModal.vue
src/components/goal/GoalRegisterConfirmModal.vue

Style: 검색 필드 폰트 수정
Style: 모달 버튼 사이 간격 추가

[Style] 검색 필드 폰트 수정 및 모달 버튼 사이 간격 추가

---

src/components/product/ProductSearchFields.vue
src/views/product/ProductList.vue

범위 설정하는 검색 필터 물결 표시 및 라벨 단일화
검색 필터 맵핑 수정

[Refactor] 상품 검색 필드 수정

---

src/components/contract/ContractDetailModal.vue
src/views/HomeView.vue
src/views/contract/ContractManagementView.vue

처리 내용
- 계약서 등록후 상세 조회 설정 초기화한거 수정
- 결재 요청 팀장, 관리자 완전 비활성화
- 팀장, 관리자 기본 홈화면 매출 관련 대시보드로 수정
>

[Refactor] : 전반적인 프론트 수정

---

src/views/contractTemplate/ContractTemplateView.vue

[Hotfix] : 계약서 양식 관리 버튼 안보이는거 수정
